In [3]:
import pandas as pd

In [5]:
p1 = pd.Series([1, 3, 6, 33, 5, 8, 9, 69, 7, 13])
p1

0     1
1     3
2     6
3    33
4     5
5     8
6     9
7    69
8     7
9    13
dtype: int64

In [7]:
p2 = pd.Series([11, 3, 5, 7, 29, 2, 88, 31, 6, 1])
p2

0    11
1     3
2     5
3     7
4    29
5     2
6    88
7    31
8     6
9     1
dtype: int64

In [9]:
pd.DataFrame({"Name":['kel','Mel', 'Ryo', 'Eal'], "Score": [55, 42, 86, 66]})

  Name  Score
0  kel     55
1  Mel     42
2  Ryo     86
3  Eal     66

In [13]:
pd.DataFrame({'Name': ['Aba', 'Bab', 'Rab'], 'Sport': ['Baskeball','Swimming', 'Running'], 'Score':[43, 25, 30]})

  Name      Sport  Score
0  Aba  Baskeball     43
1  Bab   Swimming     25
2  Rab    Running     30